### ISSUE TITLE
Script for starting server with wakeonlan

### ISSUE THREAD

**Issue by Fraguinha** [Mafiosi/Minecraft_Server_Management#1]
To be used in MacOS or Linux for people who dont like installing random python libraries

```
wakeonlan -i $(ping belezamafiosi.ddns.net -c 1 | grep PING | awk '{print $3}' | sed 's/(//;s/)//;s/://') 1C:B7:2C:B0:28:61
sleep 180
ssh mine_user@belezamafiosi.ddns.net 'cd /opt/scripts; nohup screen -S mine -d -m python3 Internal_MManager_vanilla.py &'
```

The only dependency is a program called wakeonlan

Debian based distributions:

```
$ sudo apt install wakeonlan
```

MacOS (with homebrew):

```
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; brew install wakeonlan
```

It will ask for the server password, ask your local friendly mafiosi dude for it

**Comment by Mafiosi** [comment]
Added to Instructions for both Modded and Vanilla Server
